const express=require('express');
const fs=require('fs');
const path=require('path');
const {Pool}=require('pg');
const app=express();
app.use(express.json());
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','https://convivencia-escolar-material-educativo.onrender.com');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false});
async function initDatabase(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL no configurada');await pool.query(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'));const q=await pool.query("select current_database() database");console.log('Convivencia DB connected:',q.rows[0].database);}
const ok=(res,data)=>res.json({ok:true,...data});
app.get('/health',async(req,res)=>{try{const q=await pool.query("select current_database() database,now() time");ok(res,{service:'convivencia-escolar-api',database:true,...q.rows[0]})}catch(e){res.status(500).json({ok:false,database:false})}});
app.get('/api/status',(req,res)=>ok(res,{module:'convivencia-escolar',isolation:'independent'}));
app.post('/api/establishments',async(req,res)=>{try{const {name,rbd}=req.body;if(!name)return res.status(400).json({ok:false,error:'name_required'});const q=await pool.query('insert into establishments(name,rbd) values($1,$2) on conflict(rbd) do update set name=excluded.name returning *',[name,rbd||null]);ok(res,{establishment:q.rows[0]})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/establishments',async(req,res)=>{const q=await pool.query('select * from establishments order by name');ok(res,{establishments:q.rows})});
app.post('/api/users',async(req,res)=>{try{const {establishment_id,email,rut,name,role}=req.body;if(!establishment_id||!email||!name)return res.status(400).json({ok:false,error:'required_fields'});const q=await pool.query('insert into users(establishment_id,email,rut,name,role) values($1,$2,$3,$4,$5) on conflict(establishment_id,email) do update set name=excluded.name,rut=excluded.rut,role=excluded.role returning id,establishment_id,email,rut,name,role,active,created_at',[establishment_id,email,rut||null,name,role||'professional']);ok(res,{user:q.rows[0]})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/users',async(req,res)=>{const q=await pool.query('select u.id,u.establishment_id,e.name establishment,u.email,u.rut,u.name,u.role,u.active,u.created_at from users u join establishments e on e.id=u.establishment_id order by u.name');ok(res,{users:q.rows})});
app.post('/api/courses',async(req,res)=>{try{const {establishment_id,name,school_year}=req.body;const q=await pool.query('insert into courses(establishment_id,name,school_year) values($1,$2,$3) returning *',[establishment_id,name,school_year]);ok(res,{course:q.rows[0]})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/courses',async(req,res)=>{const q=await pool.query('select c.*,e.name establishment from courses c join establishments e on e.id=c.establishment_id order by c.school_year desc,c.name');ok(res,{courses:q.rows})});
app.post('/api/students',async(req,res)=>{try{const {establishment_id,course_id,rut,name}=req.body;const q=await pool.query('insert into students(establishment_id,course_id,rut,name) values($1,$2,$3,$4) returning *',[establishment_id,course_id,rut||null,name]);ok(res,{student:q.rows[0]})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/students',async(req,res)=>{const q=await pool.query('select s.*,c.name course from students s left join courses c on c.id=s.course_id order by s.name');ok(res,{students:q.rows})});
app.post('/api/measurements',async(req,res)=>{try{const {establishment_id,code,school_year}=req.body;const q=await pool.query('insert into measurements(establishment_id,code,school_year) values($1,$2,$3) on conflict(establishment_id,code,school_year) do update set status=measurements.status returning *',[establishment_id,code,school_year]);ok(res,{measurement:q.rows[0]})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/measurements',async(req,res)=>{const q=await pool.query('select m.*,e.name establishment from measurements m join establishments e on e.id=m.establishment_id order by m.school_year desc,m.code');ok(res,{measurements:q.rows})});
app.get('/api/applications',async(req,res)=>{const q=await pool.query("select a.*,s.name student,c.name course,m.code measurement,m.school_year from survey_applications a join students s on s.id=a.student_id left join courses c on c.id=s.course_id join measurements m on m.id=a.measurement_id order by a.id desc");ok(res,{applications:q.rows})});
app.post('/api/applications',async(req,res)=>{try{const {measurement_id,student_id,survey_level}=req.body;if(!measurement_id||!student_id||!survey_level)return res.status(400).json({ok:false,error:'required_fields'});const q=await pool.query('insert into survey_applications(measurement_id,student_id,survey_level) values($1,$2,$3) on conflict(measurement_id,student_id) do update set survey_level=excluded.survey_level returning *',[measurement_id,student_id,survey_level]);ok(res,{application:q.rows[0]})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/students/:id/applications',async(req,res)=>{try{const q=await pool.query("select a.id,a.survey_level,a.status,a.started_at,a.completed_at,m.code measurement,m.school_year from survey_applications a join measurements m on m.id=a.measurement_id where a.student_id=$1 order by m.school_year,m.code",[req.params.id]);ok(res,{applications:q.rows})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/applications/:id/responses',async(req,res)=>{const client=await pool.connect();try{const responses=req.body.responses;if(!Array.isArray(responses)||!responses.length)throw new Error('responses_required');const a=await client.query('select survey_level,status from survey_applications where id=$1',[req.params.id]);if(!a.rowCount)throw new Error('application_not_found');const level=a.rows[0].survey_level;if(a.rows[0].status==='completed')throw new Error('application_already_completed');
const manifests={
'5-6':{
required:[...Array.from({length:16},(_,i)=>'D'+String(i+1).padStart(2,'0')+'_01'),'D01_02','D02_02','D03_02','D04_02','D05_02','D06_02','D07_02','D08_02','D09_02','D10_02','D13_02','D14_02',...Array.from({length:10},(_,i)=>'EXP_'+String(i+1).padStart(2,'0')),'PRO_01','PRO_02','PRO_03','BIE_01','BIE_02','BIE_03','ESC_01','ESC_02','ESC_03'],
digital:Array.from({length:6},(_,i)=>'DIG_'+String(i+1).padStart(2,'0'))
}};
const manifest=manifests[level];const seen=new Set();
for(const x of responses){if(!x||typeof x.item_code!=='string'||!Number.isInteger(x.value))throw new Error('invalid_response');if(seen.has(x.item_code))throw new Error('duplicate_item');seen.add(x.item_code);
if(manifest&&!manifest.required.includes(x.item_code)&&!manifest.digital.includes(x.item_code))throw new Error('item_not_allowed');
const isExp=x.item_code.startsWith('EXP_');const isFive=level==='5-6'&&!isExp;const max=isExp?4:(level==='1-2'?3:(isFive?5:4));if(x.value<1||x.value>max)throw new Error('value_out_of_range');}
if(manifest){for(const code of manifest.required)if(!seen.has(code))throw new Error('required_item_missing');const digitalCount=manifest.digital.filter(code=>seen.has(code)).length;if(digitalCount!==0&&digitalCount!==manifest.digital.length)throw new Error('incomplete_digital_block');}await client.query('begin');for(const x of (req.body.responses||[])){await client.query('insert into responses(application_id,item_code,value) values($1,$2,$3) on conflict(application_id,item_code) do update set value=excluded.value',[req.params.id,x.item_code,x.value])}await client.query("update survey_applications set status='completed',completed_at=now() where id=$1",[req.params.id]);await client.query('commit');ok(res,{application_id:Number(req.params.id),saved:(req.body.responses||[]).length,status:'completed'})}catch(e){await client.query('rollback');res.status(400).json({ok:false,error:e.message})}finally{client.release()}});
app.post('/api/pilot/setup',async(req,res)=>{const client=await pool.connect();try{await client.query('begin');let e=await client.query("select * from establishments where rbd='PILOTO-MEC' limit 1");if(!e.rowCount)e=await client.query("insert into establishments(name,rbd) values('Establecimiento Piloto MEC','PILOTO-MEC') returning *");const eid=e.rows[0].id;let u=await client.query("select * from users where establishment_id=$1 and email='piloto@materialeducativo.cl'",[eid]);if(!u.rowCount)u=await client.query("insert into users(establishment_id,email,name,role) values($1,'piloto@materialeducativo.cl','Profesional Piloto','professional') returning *",[eid]);let co=await client.query("select * from courses where establishment_id=$1 and name='7° A' and school_year=2026",[eid]);if(!co.rowCount)co=await client.query("insert into courses(establishment_id,name,school_year) values($1,'7° A',2026) returning *",[eid]);let st=await client.query("select * from students where establishment_id=$1 and name='Estudiante Piloto' limit 1",[eid]);if(!st.rowCount)st=await client.query("insert into students(establishment_id,course_id,name) values($1,$2,'Estudiante Piloto') returning *",[eid,co.rows[0].id]);let m=await client.query("select * from measurements where establishment_id=$1 and code='M1' and school_year=2026",[eid]);if(!m.rowCount)m=await client.query("insert into measurements(establishment_id,code,school_year) values($1,'M1',2026) returning *",[eid]);await client.query('commit');ok(res,{establishment:e.rows[0],professional:u.rows[0],course:co.rows[0],student:st.rows[0],measurement:m.rows[0]})}catch(e){await client.query('rollback');res.status(400).json({ok:false,error:e.message})}finally{client.release()}});
app.get('/api/establishments/:id/results',async(req,res)=>{try{const q=await pool.query("select a.id,a.student_id,s.course_id,r.item_code,r.value from survey_applications a join students s on s.id=a.student_id left join responses r on r.application_id=a.id where s.establishment_id=$1 and a.status='completed'",[req.params.id]);const dimensions={};const students=new Set(),courses=new Set(),applications=new Set();for(const x of q.rows){students.add(x.student_id);if(x.course_id)courses.add(x.course_id);applications.add(x.id);const k=String(x.item_code||'').slice(0,3),v=Number(x.value);if(/^D[0-9][0-9]$/.test(k)&&Number.isFinite(v))(dimensions[k]??=[]).push(v)}const dimension_summary={};for(const [k,v] of Object.entries(dimensions))dimension_summary[k]={answered:v.length,average:Number((v.reduce((a,b)=>a+b,0)/v.length).toFixed(2))};ok(res,{establishment_id:Number(req.params.id),completed_students:students.size,courses:courses.size,applications:applications.size,dimension_summary})}catch(e){res.status(400).json({ok:false,error:'institution_results_failed'})}});
app.get('/api/courses/:id/results',async(req,res)=>{try{const q=await pool.query("select a.id,a.student_id,a.survey_level,a.status,m.code measurement,m.school_year,r.item_code,r.value from survey_applications a join students s on s.id=a.student_id join measurements m on m.id=a.measurement_id left join responses r on r.application_id=a.id where s.course_id=$1 and a.status='completed' order by a.id,r.item_code",[req.params.id]);const dims={};const students=new Set();const applications=new Set();for(const x of q.rows){students.add(String(x.student_id));applications.add(String(x.id));const m=String(x.item_code||'').match(/^(D\\d{2})/);const v=Number(x.value);if(!m||!Number.isFinite(v))continue;(dims[m[1]]??=[]).push(v)}const dimension_summary=Object.fromEntries(Object.entries(dims).map(([code,v])=>[code,{answered:v.length,average:Number((v.reduce((a,b)=>a+b,0)/v.length).toFixed(2))}]));ok(res,{course_id:Number(req.params.id),completed_students:students.size,applications:applications.size,dimension_summary,note:'Agregación descriptiva para revisión profesional; no constituye diagnóstico clínico.'})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/applications/:id/results',async(req,res)=>{const a=await pool.query('select a.*,s.name student,c.name course,m.code measurement from survey_applications a join students s on s.id=a.student_id left join courses c on c.id=s.course_id join measurements m on m.id=a.measurement_id where a.id=$1',[req.params.id]);if(!a.rowCount)return res.status(404).json({ok:false,error:'not_found'});const r=await pool.query('select item_code,value from responses where application_id=$1 order by item_code',[req.params.id]);const vals=r.rows.map(x=>Number(x.value)).filter(Number.isFinite);const summary={answered:vals.length,average:vals.length?Number((vals.reduce((x,y)=>x+y,0)/vals.length).toFixed(2)):null,min:vals.length?Math.min(...vals):null,max:vals.length?Math.max(...vals):null};const groups={experience:{},protective:{},wellbeing:{},digital:{},scenarios:{}};for(const x of r.rows){const code=String(x.item_code||''),v=Number(x.value);if(!Number.isFinite(v))continue;if(code.startsWith('EXP_'))groups.experience[code]=v;else if(code.startsWith('PRO_'))groups.protective[code]=v;else if(code.startsWith('BIE_'))groups.wellbeing[code]=v;else if(code.startsWith('DIG_'))groups.digital[code]=v;else if(code.startsWith('ESC_'))groups.scenarios[code]=v;}const mean=o=>{const v=Object.values(o);return v.length?Number((v.reduce((x,y)=>x+y,0)/v.length).toFixed(2)):null};const block_summary={experience:{answered:Object.keys(groups.experience).length,frequency_mean:mean(groups.experience),note:'Frecuencia descriptiva de experiencias adversas; no se invierte ni se mezcla con dimensiones protectoras.'},protective:{answered:Object.keys(groups.protective).length,average:mean(groups.protective)},wellbeing:{answered:Object.keys(groups.wellbeing).length,average:mean(groups.wellbeing)},digital:{answered:Object.keys(groups.digital).length,average:mean(groups.digital),conditional:true},scenarios:{answered:Object.keys(groups.scenarios).length,average:mean(groups.scenarios)}};const dimensions={};for(const x of r.rows){const m=String(x.item_code||'').match(/^(D\\d{2})/);if(!m)continue;const v=Number(x.value);if(!Number.isFinite(v))continue;(dimensions[m[1]]??=[]).push(v)}const dimension_summary=Object.fromEntries(Object.entries(dimensions).map(([code,v])=>[code,{answered:v.length,average:Number((v.reduce((x,y)=>x+y,0)/v.length).toFixed(2))}]));const interpretive_profile=Object.entries(dimension_summary).map(([code,x])=>({code,average:x.average,answered:x.answered,status:'pending_validation'}));ok(res,{application:a.rows[0],responses:r.rows,summary,dimension_summary,block_summary,interpretive_profile,interpretation_note:'Los niveles interpretativos definitivos se habilitarán después de validación piloto. No constituye diagnóstico clínico.'})});
const port=process.env.PORT||3000;
initDatabase().then(()=>app.listen(port,()=>console.log('Convivencia API ready with PostgreSQL'))).catch(e=>{console.error('Convivencia startup failed:',e.message);process.exit(1)});
