window.MEC_SIMCE_BANK = {
  meta: {
    version: "2026.09.26-a",
    note: "Banco inicial de preguntas inéditas tipo SIMCE. No corresponde a una prueba oficial ni reproduce ítems reservados.",
    officialSources: [
      {label:"Ejemplos de preguntas Simce básica 2018", url:"https://archivos.agenciaeducacion.cl/EJEMPLOS_DE_PREGUNTAS_BASICA_2018.pdf"},
      {label:"Ejemplos de preguntas Simce media 2018", url:"https://archivos.agenciaeducacion.cl/EJEMPLOS_DE_PREGUNTAS_MEDIA_2018.pdf"},
      {label:"Ejemplos de preguntas Simce básica 2016", url:"https://archivos.agenciaeducacion.cl/Ejemplos_de_preguntas_Simce_basica.pdf"}
    ]
  },
  items: [
    {id:"4M-01",nivel:"4° básico",asignatura:"Matemática",eje:"Números y operaciones",habilidad:"Resolver problemas",tipo:"inédita_equivalente",enunciado:"En una biblioteca hay 6 repisas con 24 libros en cada una. ¿Cuántos libros hay en total?",opciones:["30","120","144","164"],correcta:2,justificacion:"Se calcula 6 × 24 = 144."},
    {id:"4M-02",nivel:"4° básico",asignatura:"Matemática",eje:"Fracciones",habilidad:"Representar",tipo:"inédita_equivalente",enunciado:"Una barra está dividida en 8 partes iguales y se comen 3 partes. ¿Qué fracción representa la parte que queda?",opciones:["3/8","5/8","5/3","8/5"],correcta:1,justificacion:"Quedan 5 de las 8 partes iguales."},
    {id:"4M-03",nivel:"4° básico",asignatura:"Matemática",eje:"Datos y probabilidades",habilidad:"Interpretar",tipo:"inédita_equivalente",enunciado:"En una encuesta, 12 estudiantes prefieren fútbol, 9 básquetbol y 7 natación. ¿Cuál actividad fue elegida por más estudiantes?",opciones:["Fútbol","Básquetbol","Natación","Todas por igual"],correcta:0,justificacion:"12 es la mayor frecuencia."},
    {id:"4L-01",nivel:"4° básico",asignatura:"Lectura",eje:"Comprensión",habilidad:"Localizar información",tipo:"inédita_equivalente",texto:"Cada viernes, Emilia riega las plantas de la sala antes del recreo. Esta semana llevó además una botella para limpiar las hojas.",enunciado:"¿Cuándo riega Emilia las plantas?",opciones:["Cada lunes","Cada viernes","Todos los días","Después del recreo"],correcta:1,justificacion:"El texto indica explícitamente que lo hace cada viernes."},
    {id:"4L-02",nivel:"4° básico",asignatura:"Lectura",eje:"Comprensión",habilidad:"Inferir",tipo:"inédita_equivalente",texto:"Tomás salió con paraguas aunque el cielo estaba despejado. Una hora después, comenzó una lluvia intensa.",enunciado:"¿Qué se puede inferir sobre Tomás?",opciones:["Sabía que podía llover","No quería caminar","Había perdido su mochila","Iba a regar el jardín"],correcta:0,justificacion:"Llevar paraguas anticipadamente sugiere que esperaba lluvia."},
    {id:"4L-03",nivel:"4° básico",asignatura:"Lectura",eje:"Comprensión",habilidad:"Reflexionar",tipo:"inédita_equivalente",texto:"El cartel dice: 'Trae tu botella reutilizable y ayúdanos a reducir los residuos en la escuela'.",enunciado:"¿Cuál es el propósito principal del cartel?",opciones:["Vender botellas","Contar una historia","Promover una acción de cuidado ambiental","Explicar cómo fabricar plástico"],correcta:2,justificacion:"Busca motivar una conducta concreta de reducción de residuos."},
    {id:"6M-01",nivel:"6° básico",asignatura:"Matemática",eje:"Números y operaciones",habilidad:"Resolver problemas",tipo:"inédita_equivalente",enunciado:"Se deben guardar 154 cuadernos en cajas de 12. ¿Cuántas cajas completas se pueden llenar y cuántos cuadernos sobran?",opciones:["12 cajas y sobran 10","13 cajas y sobran 2","12 cajas y sobran 2","14 cajas y sobra 1"],correcta:0,justificacion:"12 × 12 = 144 y 154 − 144 = 10."},
    {id:"6M-02",nivel:"6° básico",asignatura:"Matemática",eje:"Patrones y álgebra",habilidad:"Resolver",tipo:"inédita_equivalente",enunciado:"Si x + 7 < 12, ¿cuál de estos valores puede tomar x?",opciones:["8","6","5","4"],correcta:3,justificacion:"Con x=4 se obtiene 11<12; los demás no cumplen estrictamente la desigualdad."},
    {id:"6M-03",nivel:"6° básico",asignatura:"Matemática",eje:"Decimales",habilidad:"Comparar",tipo:"inédita_equivalente",enunciado:"¿Cuál de los siguientes números es mayor?",opciones:["2,35","2,305","2,53","2,503"],correcta:2,justificacion:"2,53 = 2,530 y es mayor que las otras opciones."},
    {id:"6L-01",nivel:"6° básico",asignatura:"Lectura",eje:"Comprensión",habilidad:"Localizar",tipo:"inédita_equivalente",texto:"El humedal abre sus senderos al público de martes a domingo entre las 9:00 y las 17:00. Los lunes se realizan labores de mantención.",enunciado:"¿Por qué el humedal no recibe público los lunes?",opciones:["Por falta de visitantes","Por labores de mantención","Porque cierra a las 17:00","Por actividades escolares"],correcta:1,justificacion:"La causa está expresamente indicada en el texto."},
    {id:"6L-02",nivel:"6° básico",asignatura:"Lectura",eje:"Comprensión",habilidad:"Inferir",tipo:"inédita_equivalente",texto:"Al terminar la exposición, Camila miró sus apuntes, sonrió y guardó lentamente las tarjetas que había preparado durante toda la semana.",enunciado:"¿Qué se puede inferir sobre Camila?",opciones:["Quedó satisfecha con su exposición","Olvidó completamente el tema","No había preparado nada","Quería repetir de inmediato"],correcta:0,justificacion:"La sonrisa y el cuidado con sus materiales sugieren satisfacción."},
    {id:"6L-03",nivel:"6° básico",asignatura:"Lectura",eje:"Comprensión",habilidad:"Evaluar información",tipo:"inédita_equivalente",texto:"Un aviso escolar afirma: 'Dormir entre 9 y 11 horas ayuda a mantener la atención durante el día'.",enunciado:"¿Qué información adicional permitiría evaluar mejor esa afirmación?",opciones:["El color del aviso","La fuente o estudio que respalda el dato","El nombre del curso que lo leyó","El tamaño de la letra"],correcta:1,justificacion:"Conocer la fuente permite valorar la confiabilidad de la afirmación."},
    {id:"2M-M01",nivel:"II medio",asignatura:"Matemática",eje:"Álgebra y funciones",habilidad:"Modelar",tipo:"inédita_equivalente",enunciado:"Un servicio cobra $2.000 fijos más $350 por cada kilómetro recorrido. ¿Qué expresión representa el costo C para x kilómetros?",opciones:["C=2350x","C=2000x+350","C=2000+350x","C=350+2000/x"],correcta:2,justificacion:"El costo total suma una tarifa fija y una parte proporcional a la distancia."},
    {id:"2M-M02",nivel:"II medio",asignatura:"Matemática",eje:"Probabilidad",habilidad:"Calcular",tipo:"inédita_equivalente",enunciado:"En una caja hay 5 fichas rojas, 3 azules y 2 verdes. Si se extrae una ficha al azar, ¿cuál es la probabilidad de que sea azul?",opciones:["3/5","3/10","1/3","2/10"],correcta:1,justificacion:"Hay 3 casos favorables de 10 fichas en total."},
    {id:"2M-M03",nivel:"II medio",asignatura:"Matemática",eje:"Datos",habilidad:"Interpretar",tipo:"inédita_equivalente",enunciado:"Las edades de cinco estudiantes son 15, 15, 16, 16 y 18 años. ¿Cuál es la mediana?",opciones:["15","16","16,5","18"],correcta:1,justificacion:"Ordenados los datos, el valor central es 16."},
    {id:"2M-L01",nivel:"II medio",asignatura:"Lectura",eje:"Comprensión",habilidad:"Identificar tesis",tipo:"inédita_equivalente",texto:"Permitir más espacios de lectura libre en la jornada escolar no significa dejar de enseñar contenidos. Al contrario, puede ampliar el vocabulario, mejorar la comprensión y acercar a los estudiantes a distintos temas.",enunciado:"¿Cuál es la idea principal del texto?",opciones:["La lectura libre reemplaza todas las clases","La lectura libre puede aportar al aprendizaje","El vocabulario solo se aprende leyendo novelas","Los contenidos escolares deberían eliminarse"],correcta:1,justificacion:"El texto defiende que la lectura libre puede complementar y fortalecer el aprendizaje."},
    {id:"2M-L02",nivel:"II medio",asignatura:"Lectura",eje:"Comprensión",habilidad:"Inferir postura",tipo:"inédita_equivalente",texto:"Aunque la inteligencia artificial puede apoyar tareas escolares, entregar una respuesta sin revisarla impide aprender de los errores y evaluar si la información es correcta.",enunciado:"¿Qué postura adopta el autor?",opciones:["Rechaza todo uso de inteligencia artificial","Promueve un uso crítico y responsable","Sostiene que siempre entrega respuestas correctas","Afirma que reemplaza al profesorado"],correcta:1,justificacion:"La crítica no es al uso en sí, sino a aceptar respuestas sin revisión."},
    {id:"2M-L03",nivel:"II medio",asignatura:"Lectura",eje:"Comprensión",habilidad:"Evaluar argumentos",tipo:"inédita_equivalente",texto:"Una columna sostiene que ampliar las áreas verdes mejora la calidad de vida porque reduce la temperatura urbana y crea espacios de encuentro comunitario.",enunciado:"¿Cuál sería la mejor evidencia para respaldar el argumento?",opciones:["Una fotografía de un parque bonito","Datos comparativos de temperatura y uso de parques","La opinión de una sola persona","El precio de las viviendas de otra ciudad"],correcta:1,justificacion:"Los datos comparativos se relacionan directamente con los efectos mencionados."}
  ]
};
