(()=>{const A=window.MEC78,root=document.querySelector('.question'),answers={};if(!A||!root)return;
const standard=[['Nunca',1],['Casi nunca',2],['A veces',3],['Casi siempre',4],['Siempre',5]];
const frequency=[['Nunca',1],['Una vez',2],['Algunas veces',3],['Muchas veces',4]];
const likely=[['Nada probable',1],['Poco probable',2],['Algo probable',3],['Bastante probable',4],['Muy probable',5]];
const base=[...A.core.map(x=>({code:x[0],text:x[2],scale:standard})),...A.experience.map(x=>({code:x[0],text:x[1],scale:frequency})),...A.peer.map(x=>({code:x[0],text:x[1],scale:standard})),...A.wellbeing.map(x=>({code:x[0],text:x[1],scale:standard})),...A.scenarios.map(x=>({code:x[0],text:x[1],scale:likely}))];
let digital=null,idx=0,submitting=false;const KEY='mec78_'+(MECSurvey.applicationId||'sin_app'),META=KEY+'_meta';
try{Object.assign(answers,JSON.parse(sessionStorage.getItem(KEY)||'{}'));const m=JSON.parse(sessionStorage.getItem(META)||'{}');if(typeof m.digital==='boolean')digital=m.digital;if(Number.isInteger(m.idx)&&m.idx>=0)idx=m.idx}catch(e){}
const persist=()=>{try{sessionStorage.setItem(KEY,JSON.stringify(answers));sessionStorage.setItem(META,JSON.stringify({idx,digital}))}catch(e){}};
function items(){return digital===true?[...base,...A.digital.map(x=>({code:x[0],text:x[1],scale:standard}))]:base}
function render(){const all=items();if(idx>=all.length){if(digital===true){submit();return}decision();return}const x=all[idx];root.innerHTML='<div class="qmeta"><span class="qnum">PREGUNTA '+(idx+1)+' DE '+all.length+'</span><button type="button" class="audio" id="listen">🔊 Escuchar</button></div><h1 id="q" tabindex="-1"></h1><div class="answers" id="opts"></div><div class="survey-foot"><button type="button" class="btn secondary" id="prev">← Anterior</button><span class="autosave">Avance protegido en este dispositivo</span><button type="button" class="btn primary" id="next">Siguiente →</button></div>';const q=document.getElementById('q');q.textContent=x.text;q.focus();const o=document.getElementById('opts');x.scale.forEach(([label,value])=>{const b=document.createElement('button');b.type='button';b.className='answer'+(answers[x.code]===value?' selected':'');b.setAttribute('aria-pressed',answers[x.code]===value?'true':'false');b.textContent=label;b.onclick=()=>{answers[x.code]=value;persist();render()};o.appendChild(b)});document.getElementById('listen').onclick=()=>{if(!window.MECVoice||!MECVoice.speak(x.text))alert('La lectura en voz alta no está disponible en este dispositivo.')};document.getElementById('prev').onclick=()=>{if(idx>0){idx--;persist();render()}};document.getElementById('next').onclick=()=>{if(answers[x.code]==null){alert('Selecciona una respuesta para continuar.');return}idx++;persist();render()};const p=document.querySelector('.progress span');if(p){const pct=Math.round(idx/all.length*100);p.style.width=pct+'%';p.setAttribute('role','progressbar');p.setAttribute('aria-valuemin','0');p.setAttribute('aria-valuemax','100');p.setAttribute('aria-valuenow',String(pct));p.setAttribute('aria-label','Avance de la encuesta')}}
function decision(){root.innerHTML='<h1 tabindex="-1">Antes de terminar</h1><p>¿Usas internet, redes sociales, mensajería, juegos en línea o algún dispositivo digital?</p><div class="answers"><button type="button" class="answer" id="yes">Sí</button><button type="button" class="answer" id="no">No</button></div><div class="survey-foot"><button type="button" class="btn secondary" id="back">← Volver</button></div>';root.querySelector('h1').focus();document.getElementById('back').onclick=()=>{idx=Math.max(0,base.length-1);persist();render()};document.getElementById('yes').onclick=()=>{digital=true;idx=base.length;persist();render()};document.getElementById('no').onclick=()=>{digital=false;A.digital.forEach(x=>delete answers[x[0]]);persist();submit()}}
async function submit(){if(submitting)return;submitting=true;if(base.some(x=>answers[x.code]==null)){submitting=false;idx=0;render();return}if(digital===true&&A.digital.some(x=>answers[x[0]]==null)){submitting=false;idx=base.length;render();return}try{const saved=await MECSurvey.save(Object.entries(answers).map(([item_code,value])=>({item_code,value})));sessionStorage.removeItem(KEY);sessionStorage.removeItem(META);location.href=saved.next}catch(e){submitting=false;root.innerHTML='<h1 tabindex="-1">Tus respuestas siguen guardadas</h1><p role="alert">No fue posible enviarlas todavía. Puedes reintentar sin responder nuevamente.</p><div class="survey-foot"><button type="button" class="btn primary" id="retry">Reintentar envío</button><button type="button" class="btn secondary" id="review">Revisar respuestas</button></div>';root.querySelector('h1').focus();document.getElementById('retry').onclick=submit;document.getElementById('review').onclick=()=>{idx=0;persist();render()}}}
async function start(){if(!MECSurvey.applicationId){root.innerHTML='<h1>Acceso no válido</h1><p>Esta encuesta necesita una aplicación asignada por el establecimiento.</p>';return}try{const d=await MECSurvey.context();if(d.application.survey_level!=='7-8'){root.innerHTML='<h1>Instrumento no correspondiente</h1><p>La aplicación asignada pertenece a otro nivel educativo.</p>';return}if(d.application.status==='completed'){root.innerHTML='<h1>Aplicación ya completada</h1><p>Las respuestas de esta aplicación ya fueron registradas.</p>';return}render()}catch(e){root.innerHTML='<h1>No fue posible validar el acceso</h1><p>Revisa la conexión e inténtalo nuevamente.</p>'}}start()})();