window.MEC56={
core:[
['D01_01','D01','Me siento seguro o segura en los distintos espacios de mi escuela.'],['D02_01','D02','En mi curso nos tratamos con respeto, incluso cuando pensamos distinto.'],['D03_01','D03','Tengo compañeros o compañeras con quienes puedo contar.'],['D04_01','D04','Puedo participar en mi curso sin temor a burlas, amenazas o agresiones.'],['D05_01','D05','Conozco las normas de convivencia y entiendo para qué sirven.'],['D06_01','D06','Cuando surge un conflicto, podemos buscar soluciones sin agredirnos.'],['D07_01','D07','En mi curso se respetan las diferencias entre las personas.'],['D08_01','D08','Siento que formo parte de mi curso.'],['D09_01','D09','Siento que mi opinión puede ser considerada en asuntos del curso.'],['D10_01','D10','La mayor parte del tiempo me siento bien en la escuela.'],['D11_01','D11','Cuando una emoción es muy intensa, conozco formas de calmarme o pedir apoyo.'],['D12_01','D12','Confío en mi capacidad para aprender y mejorar.'],['D13_01','D13','Sé a qué adulto de la escuela acudir si necesito ayuda.'],['D14_01','D14','Cuando un estudiante informa un problema, los adultos de la escuela lo toman en serio.'],['D15_01','D15','Sé cómo proteger mi privacidad y seguridad cuando uso internet o dispositivos.'],['D16_01','D16','Cuando alguien necesita apoyo, puedo ayudar sin ponerme en riesgo.'],
['D01_02','D01','Los recreos y espacios comunes se sienten seguros para mí.'],['D02_02','D02','Podemos equivocarnos o expresar ideas sin recibir humillaciones.'],['D03_02','D03','Cuando trabajamos en grupo, siento que puedo participar.'],['D04_02','D04','Si alguien me molesta o agrede, siento que puedo pedir que pare o buscar ayuda.'],['D05_02','D05','Las normas se aplican de manera justa.'],['D06_02','D06','Después de un conflicto, podemos reparar el daño y seguir conviviendo.'],['D07_02','D07','Nadie debería ser excluido por su forma de ser, origen, características o necesidades.'],['D08_02','D08','Me siento aceptado o aceptada por mi curso.'],['D09_02','D09','Los estudiantes tenemos oportunidades reales de proponer mejoras.'],['D10_02','D10','Puedo concentrarme y participar sin sentirme constantemente preocupado o incómodo.'],['D13_02','D13','Hay al menos un adulto de la escuela en quien confío.'],['D14_02','D14','Sé que la escuela puede actuar cuando ocurre una situación de maltrato.']],
experience:[
['EXP_01','Me han empujado, golpeado o hecho daño a propósito.'],['EXP_02','Se han burlado de mí o me han puesto apodos para hacerme sentir mal.'],['EXP_03','Me han excluido a propósito de grupos, juegos o actividades.'],['EXP_04','Me han quitado, escondido o dañado mis pertenencias para molestarme.'],['EXP_05','Me han amenazado, intimidado o asustado.'],['EXP_06','Han difundido rumores o comentarios sobre mí para perjudicarme.'],['EXP_07','Me han presionado u obligado a hacer algo que no quería.'],['EXP_08','He evitado lugares, actividades o personas de la escuela por temor a que me molesten o agredan.'],['EXP_09','Me han molestado de forma repetida aunque intenté alejarme o pedí que pararan.'],['EXP_10','He sentido que no podía defenderme o conseguir que una situación de maltrato se detuviera.']],
protective:[
['PRO_01','Si algo me hace sentir inseguro o insegura, sé cómo pedir ayuda a un adulto.'],['PRO_02','Si veo que alguien está siendo maltratado, sé cómo buscar ayuda sin ponerme en riesgo.'],['PRO_03','Creo que pedir ayuda cuando algo me preocupa es una forma de cuidarme.']],
digital:[
['DIG_01','Protejo mis datos personales, contraseñas e información privada.'],['DIG_02','Sé qué hacer si recibo mensajes, imágenes o comentarios que me hacen sentir mal.'],['DIG_03','Pido permiso antes de compartir fotos, videos o información de otras personas.'],['DIG_04','Evito reenviar contenido que humille, amenace o haga daño a alguien.'],['DIG_05','Sé cómo bloquear, guardar evidencia o pedir ayuda frente a una situación digital que me preocupa.'],['DIG_06','Sé a qué adulto acudir si ocurre un problema en internet, redes, juegos o mensajería.']],
wellbeing:[
['BIE_01','Durante las últimas semanas me ha resultado posible sentirme tranquilo o tranquila en la escuela.'],['BIE_02','Durante las últimas semanas he podido disfrutar o interesarme por actividades de la escuela.'],['BIE_03','Cuando algo me preocupa en la escuela, siento que cuento con apoyo.']],
scenarios:[
['ESC_01','Ves que un grupo se burla repetidamente de un compañero. ¿Qué tan probable es que busques ayuda de un adulto sin exponerte?'],['ESC_02','Recibes una imagen humillante de otro estudiante en un chat. ¿Qué tan probable es que evites reenviarla y busques una forma segura de ayudar?'],['ESC_03','Tienes un conflicto con un compañero. ¿Qué tan probable es que intentes resolverlo sin amenazas ni agresiones?']]
};